
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8" />
        <title>Ultime sacrifice pour la patrie</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&family=Special+Elite&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="assets/css/style.css" />
    </head>
    <body>
        <!-- le code HTML de la page -->
        <header>
            <h1>Ultime sacrifice pour la patrie<br>
            L'histoire du feu major Mbumb Mbang assassiné à Kinshasa en 1998.
            </h1>
        </header>
        
        <main>
            <section>
                <h2>Préface</h2>
                <p>
                  Richard Mbumb Mbang est né à Kapanga (Katanga) en 1956. Il fut commando ranger formé aux Etats Unis d'Amérique sous la reigne du feu président Mobutu.
                </p>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
                  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
                </p>
            </section>
            
           <section>
               <h2>Quelle partie de l'histoire voulez-vous lire ?</h2>
               <div>
                   <form method="get" action="principal.php">
                <div>
                    <label for="choice-1">Biographie du feu major Mbumb</label>
                    <input type="radio" id="choice-1" name="choice" value="choice-1">
                </div>
                <div>
                    <label for="choice-2">Vie militaire du feu major Mbumb</label>
                    <input type="radio" id="choice-2" name="choice" value="choice-2">
                </div>
                <div>
                    <label for="choice-3">Assassinat du feu major Mbumb</label>
                    <input type="radio" id="choice-3" name="choice" value="choice-3">
                </div>
                <div>
                    <input type="submit" value="Valider le choix" />
                </div>
            </form>
        </div>
    </section>
    
          
            
        </main>
        
       <footer>
           
       </footer>
       
    </body>
</html>